# Generated by Django 5.0.3 on 2024-04-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0013_tabela_realizado_uuid_conta_contabil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela_realizado',
            old_name='vencimento',
            new_name='due_date',
        ),
    ]
