# Generated by Django 5.0.3 on 2024-04-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0014_rename_vencimento_tabela_realizado_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabela_realizado',
            new_name='SettledEntry',
        ),
    ]
