# Generated by Django 5.0.3 on 2024-04-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0015_rename_tabela_realizado_settledentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='descricao',
            new_name='description',
        ),
    ]
