# Generated by Django 5.0.3 on 2024-04-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0016_rename_descricao_settledentry_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='observacao',
            new_name='observation',
        ),
    ]
