# Generated by Django 5.0.3 on 2024-04-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0018_rename_valor_settledentry_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='conta_contabil',
            new_name='general_ledger_account',
        ),
    ]
