# Generated by Django 5.0.3 on 2024-04-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0019_rename_conta_contabil_settledentry_general_ledger_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='uuid_conta_contabil',
            new_name='uuid_general_ledger_account',
        ),
    ]
