# Generated by Django 5.0.3 on 2024-04-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0020_rename_uuid_conta_contabil_settledentry_uuid_general_ledger_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='parcela_atual',
            new_name='current_installment',
        ),
    ]
