# Generated by Django 5.0.3 on 2024-04-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0021_rename_parcela_atual_settledentry_current_installment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='parcelas_total',
            new_name='total_installments',
        ),
    ]
