# Generated by Django 5.0.3 on 2024-04-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0022_rename_parcelas_total_settledentry_total_installments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='natureza',
            new_name='transaction_type',
        ),
    ]
