# Generated by Django 5.0.3 on 2024-04-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0023_rename_natureza_settledentry_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='original_data_criacao',
            new_name='original_creation_date',
        ),
    ]
