# Generated by Django 5.0.3 on 2024-04-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0025_rename_uuid_correlacao_settledentry_uuid_correlation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totais_mes_realizado',
            old_name='inicio_mes',
            new_name='start_of_month',
        ),
    ]
