# Generated by Django 5.0.3 on 2024-04-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0026_rename_inicio_mes_totais_mes_realizado_start_of_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totais_mes_realizado',
            old_name='fim_mes',
            new_name='end_of_month',
        ),
    ]
