# Generated by Django 5.0.3 on 2024-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0027_rename_fim_mes_totais_mes_realizado_end_of_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totais_mes_realizado',
            old_name='data_formatada',
            new_name='formatted_date',
        ),
    ]
