# Generated by Django 5.0.3 on 2024-04-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0028_rename_data_formatada_totais_mes_realizado_formatted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totais_mes_realizado',
            old_name='saldo_mensal',
            new_name='monthly_balance',
        ),
        migrations.RenameField(
            model_name='totais_mes_realizado',
            old_name='total_credito',
            new_name='total_credit',
        ),
        migrations.RenameField(
            model_name='totais_mes_realizado',
            old_name='total_debito',
            new_name='total_debit',
        ),
    ]
