# Generated by Django 5.0.3 on 2024-04-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0029_rename_saldo_mensal_totais_mes_realizado_monthly_balance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Totais_mes_realizado',
            new_name='MonthsListSettled',
        ),
    ]
