# Generated by Django 5.0.3 on 2024-04-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0030_rename_totais_mes_realizado_monthslistsettled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='data_liquidacao',
            new_name='settlement_date',
        ),
    ]
