# Generated by Django 5.0.3 on 2024-04-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0031_rename_data_liquidacao_settledentry_settlement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='banco_liquidacao',
            new_name='settlement_bank',
        ),
        migrations.RenameField(
            model_name='settledentry',
            old_name='banco_id_liquidacao',
            new_name='settlement_bank_id',
        ),
    ]
