# Generated by Django 5.0.3 on 2024-04-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0032_rename_banco_liquidacao_settledentry_settlement_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='uuid_correlation_parcelas',
            new_name='uuid_correlation_installments',
        ),
    ]
