# Generated by Django 5.0.3 on 2024-04-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0033_rename_uuid_correlation_parcelas_settledentry_uuid_correlation_installments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settledentry',
            old_name='fluxo_id',
            new_name='cash_flow_id',
        ),
    ]
