# Generated by Django 5.0.3 on 2024-04-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0048_rename_tabelatemporaria_temporarytable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Months_list_cash_flow',
            new_name='MonthsListCashFlow',
        ),
    ]
