# Generated by Django 5.0.3 on 2024-04-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0051_rename_bancos_banks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='agencia',
            new_name='bank_branch',
        ),
    ]
