# Generated by Django 5.0.3 on 2024-04-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0056_rename_departamentos_departments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='uuid_departamento',
            new_name='uuid_department',
        ),
    ]
